/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null } |
  { 'preferNotToSay' : null };
export interface PaymentRequest {
  'id' : bigint,
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'user' : Principal,
  'timestamp' : Time,
  'amount' : bigint,
}
export type Time = bigint;
export interface TournamentMatch {
  'id' : bigint,
  'status' : { 'upcoming' : null } |
    { 'live' : null } |
    { 'completed' : null },
  'title' : string,
  'maxSlots' : bigint,
  'scheduledTime' : Time,
  'mode' : string,
  'roomPassword' : [] | [string],
  'category' : { 'BattleRoyale' : null } |
    { 'other' : null } |
    { 'ClashSquad' : null } |
    { 'LoneWolf' : null },
  'entryFee' : bigint,
  'roomId' : [] | [string],
  'filledSlots' : bigint,
  'prizePool' : bigint,
}
export interface UserProfile {
  'languagePreference' : string,
  'username' : string,
  'phoneNumbers' : Array<string>,
  'winningBalance' : bigint,
  'registeredMatches' : Array<bigint>,
  'email' : string,
  'gender' : Gender,
  'transactions' : Array<WalletTransaction>,
  'lastName' : string,
  'walletBalance' : bigint,
  'firstName' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WalletTransaction {
  'id' : bigint,
  'status' : { 'pending' : null } |
    { 'completed' : null },
  'transactionType' : { 'withdraw' : null } |
    { 'deposit' : null } |
    { 'entryFee' : null } |
    { 'winning' : null },
  'description' : string,
  'timestamp' : Time,
  'amount' : bigint,
}
export interface WithdrawRequest {
  'id' : bigint,
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'user' : Principal,
  'timestamp' : Time,
  'upiId' : string,
  'amount' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMatch' : ActorMethod<[TournamentMatch], undefined>,
  'addMatchWithToken' : ActorMethod<[string, TournamentMatch], undefined>,
  'addWinningAmountWithToken' : ActorMethod<
    [string, Principal, bigint],
    undefined
  >,
  'approvePaymentRequest' : ActorMethod<[bigint], undefined>,
  'approvePaymentWithToken' : ActorMethod<[string, bigint], undefined>,
  'approveWithdrawWithToken' : ActorMethod<[string, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkEmailExists' : ActorMethod<[string], boolean>,
  'checkPhoneExists' : ActorMethod<[string], boolean>,
  'checkUsernameExists' : ActorMethod<[string], boolean>,
  'deleteMatchWithToken' : ActorMethod<[string, bigint], undefined>,
  'getAllMatches' : ActorMethod<[], Array<TournamentMatch>>,
  'getAllPendingPaymentsWithToken' : ActorMethod<
    [string],
    Array<PaymentRequest>
  >,
  'getAllPendingWithdrawsWithToken' : ActorMethod<
    [string],
    Array<WithdrawRequest>
  >,
  'getAllUsersWithToken' : ActorMethod<
    [string],
    Array<{ 'principal' : Principal, 'username' : string }>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMatchesByCategory' : ActorMethod<
    [
      { 'BattleRoyale' : null } |
        { 'other' : null } |
        { 'ClashSquad' : null } |
        { 'LoneWolf' : null },
    ],
    Array<TournamentMatch>
  >,
  'getRegisteredMatches' : ActorMethod<[], Array<TournamentMatch>>,
  'getTransactionHistory' : ActorMethod<[], Array<WalletTransaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWalletBalance' : ActorMethod<[], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerForMatch' : ActorMethod<[bigint], undefined>,
  'rejectPaymentWithToken' : ActorMethod<[string, bigint], undefined>,
  'rejectWithdrawWithToken' : ActorMethod<[string, bigint], undefined>,
  'requestPayment' : ActorMethod<[bigint], undefined>,
  'requestWithdraw' : ActorMethod<[bigint, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateMatchWithToken' : ActorMethod<[string, TournamentMatch], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];