/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const TournamentMatch = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'upcoming' : IDL.Null,
    'live' : IDL.Null,
    'completed' : IDL.Null,
  }),
  'title' : IDL.Text,
  'maxSlots' : IDL.Nat,
  'scheduledTime' : Time,
  'mode' : IDL.Text,
  'roomPassword' : IDL.Opt(IDL.Text),
  'category' : IDL.Variant({
    'BattleRoyale' : IDL.Null,
    'other' : IDL.Null,
    'ClashSquad' : IDL.Null,
    'LoneWolf' : IDL.Null,
  }),
  'entryFee' : IDL.Int,
  'roomId' : IDL.Opt(IDL.Text),
  'filledSlots' : IDL.Nat,
  'prizePool' : IDL.Int,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
  'preferNotToSay' : IDL.Null,
});
export const WalletTransaction = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({ 'pending' : IDL.Null, 'completed' : IDL.Null }),
  'transactionType' : IDL.Variant({
    'withdraw' : IDL.Null,
    'deposit' : IDL.Null,
    'entryFee' : IDL.Null,
  }),
  'description' : IDL.Text,
  'timestamp' : Time,
  'amount' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'languagePreference' : IDL.Text,
  'username' : IDL.Text,
  'phoneNumbers' : IDL.Vec(IDL.Text),
  'registeredMatches' : IDL.Vec(IDL.Nat),
  'gender' : Gender,
  'transactions' : IDL.Vec(WalletTransaction),
  'lastName' : IDL.Text,
  'walletBalance' : IDL.Int,
  'firstName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMatch' : IDL.Func([TournamentMatch], [], []),
  'approvePaymentRequest' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllMatches' : IDL.Func([], [IDL.Vec(TournamentMatch)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMatchesByCategory' : IDL.Func(
      [
        IDL.Variant({
          'BattleRoyale' : IDL.Null,
          'other' : IDL.Null,
          'ClashSquad' : IDL.Null,
          'LoneWolf' : IDL.Null,
        }),
      ],
      [IDL.Vec(TournamentMatch)],
      ['query'],
    ),
  'getRegisteredMatches' : IDL.Func([], [IDL.Vec(TournamentMatch)], ['query']),
  'getTransactionHistory' : IDL.Func(
      [],
      [IDL.Vec(WalletTransaction)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWalletBalance' : IDL.Func([], [IDL.Int], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerForMatch' : IDL.Func([IDL.Nat], [], []),
  'requestPayment' : IDL.Func([IDL.Int], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const TournamentMatch = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'upcoming' : IDL.Null,
      'live' : IDL.Null,
      'completed' : IDL.Null,
    }),
    'title' : IDL.Text,
    'maxSlots' : IDL.Nat,
    'scheduledTime' : Time,
    'mode' : IDL.Text,
    'roomPassword' : IDL.Opt(IDL.Text),
    'category' : IDL.Variant({
      'BattleRoyale' : IDL.Null,
      'other' : IDL.Null,
      'ClashSquad' : IDL.Null,
      'LoneWolf' : IDL.Null,
    }),
    'entryFee' : IDL.Int,
    'roomId' : IDL.Opt(IDL.Text),
    'filledSlots' : IDL.Nat,
    'prizePool' : IDL.Int,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
    'preferNotToSay' : IDL.Null,
  });
  const WalletTransaction = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({ 'pending' : IDL.Null, 'completed' : IDL.Null }),
    'transactionType' : IDL.Variant({
      'withdraw' : IDL.Null,
      'deposit' : IDL.Null,
      'entryFee' : IDL.Null,
    }),
    'description' : IDL.Text,
    'timestamp' : Time,
    'amount' : IDL.Int,
  });
  const UserProfile = IDL.Record({
    'languagePreference' : IDL.Text,
    'username' : IDL.Text,
    'phoneNumbers' : IDL.Vec(IDL.Text),
    'registeredMatches' : IDL.Vec(IDL.Nat),
    'gender' : Gender,
    'transactions' : IDL.Vec(WalletTransaction),
    'lastName' : IDL.Text,
    'walletBalance' : IDL.Int,
    'firstName' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMatch' : IDL.Func([TournamentMatch], [], []),
    'approvePaymentRequest' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllMatches' : IDL.Func([], [IDL.Vec(TournamentMatch)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMatchesByCategory' : IDL.Func(
        [
          IDL.Variant({
            'BattleRoyale' : IDL.Null,
            'other' : IDL.Null,
            'ClashSquad' : IDL.Null,
            'LoneWolf' : IDL.Null,
          }),
        ],
        [IDL.Vec(TournamentMatch)],
        ['query'],
      ),
    'getRegisteredMatches' : IDL.Func(
        [],
        [IDL.Vec(TournamentMatch)],
        ['query'],
      ),
    'getTransactionHistory' : IDL.Func(
        [],
        [IDL.Vec(WalletTransaction)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWalletBalance' : IDL.Func([], [IDL.Int], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerForMatch' : IDL.Func([IDL.Nat], [], []),
    'requestPayment' : IDL.Func([IDL.Int], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };