/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const TournamentMatch = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'upcoming' : IDL.Null,
    'live' : IDL.Null,
    'completed' : IDL.Null,
  }),
  'title' : IDL.Text,
  'maxSlots' : IDL.Nat,
  'scheduledTime' : Time,
  'mode' : IDL.Text,
  'roomPassword' : IDL.Opt(IDL.Text),
  'category' : IDL.Variant({
    'BattleRoyale' : IDL.Null,
    'other' : IDL.Null,
    'ClashSquad' : IDL.Null,
    'LoneWolf' : IDL.Null,
  }),
  'entryFee' : IDL.Int,
  'roomId' : IDL.Opt(IDL.Text),
  'filledSlots' : IDL.Nat,
  'prizePool' : IDL.Int,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PaymentRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'user' : IDL.Principal,
  'timestamp' : Time,
  'amount' : IDL.Int,
});
export const WithdrawRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'user' : IDL.Principal,
  'timestamp' : Time,
  'upiId' : IDL.Text,
  'amount' : IDL.Int,
});
export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
  'preferNotToSay' : IDL.Null,
});
export const WalletTransaction = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({ 'pending' : IDL.Null, 'completed' : IDL.Null }),
  'transactionType' : IDL.Variant({
    'withdraw' : IDL.Null,
    'deposit' : IDL.Null,
    'entryFee' : IDL.Null,
    'winning' : IDL.Null,
  }),
  'description' : IDL.Text,
  'timestamp' : Time,
  'amount' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'languagePreference' : IDL.Text,
  'username' : IDL.Text,
  'phoneNumbers' : IDL.Vec(IDL.Text),
  'winningBalance' : IDL.Int,
  'registeredMatches' : IDL.Vec(IDL.Nat),
  'email' : IDL.Text,
  'gender' : Gender,
  'transactions' : IDL.Vec(WalletTransaction),
  'lastName' : IDL.Text,
  'walletBalance' : IDL.Int,
  'firstName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMatch' : IDL.Func([TournamentMatch], [], []),
  'addMatchWithToken' : IDL.Func([IDL.Text, TournamentMatch], [], []),
  'addWinningAmountWithToken' : IDL.Func(
      [IDL.Text, IDL.Principal, IDL.Int],
      [],
      [],
    ),
  'approvePaymentRequest' : IDL.Func([IDL.Nat], [], []),
  'approvePaymentWithToken' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'approveWithdrawWithToken' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkEmailExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'checkPhoneExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'checkUsernameExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'deleteMatchWithToken' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'getAllMatches' : IDL.Func([], [IDL.Vec(TournamentMatch)], ['query']),
  'getAllPendingPaymentsWithToken' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PaymentRequest)],
      ['query'],
    ),
  'getAllPendingWithdrawsWithToken' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(WithdrawRequest)],
      ['query'],
    ),
  'getAllUsersWithToken' : IDL.Func(
      [IDL.Text],
      [
        IDL.Vec(
          IDL.Record({ 'principal' : IDL.Principal, 'username' : IDL.Text })
        ),
      ],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMatchesByCategory' : IDL.Func(
      [
        IDL.Variant({
          'BattleRoyale' : IDL.Null,
          'other' : IDL.Null,
          'ClashSquad' : IDL.Null,
          'LoneWolf' : IDL.Null,
        }),
      ],
      [IDL.Vec(TournamentMatch)],
      ['query'],
    ),
  'getRegisteredMatches' : IDL.Func([], [IDL.Vec(TournamentMatch)], ['query']),
  'getTransactionHistory' : IDL.Func(
      [],
      [IDL.Vec(WalletTransaction)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWalletBalance' : IDL.Func([], [IDL.Int], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerForMatch' : IDL.Func([IDL.Nat], [], []),
  'rejectPaymentWithToken' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'rejectWithdrawWithToken' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'requestPayment' : IDL.Func([IDL.Int], [], []),
  'requestWithdraw' : IDL.Func([IDL.Int, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateMatchWithToken' : IDL.Func([IDL.Text, TournamentMatch], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const TournamentMatch = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'upcoming' : IDL.Null,
      'live' : IDL.Null,
      'completed' : IDL.Null,
    }),
    'title' : IDL.Text,
    'maxSlots' : IDL.Nat,
    'scheduledTime' : Time,
    'mode' : IDL.Text,
    'roomPassword' : IDL.Opt(IDL.Text),
    'category' : IDL.Variant({
      'BattleRoyale' : IDL.Null,
      'other' : IDL.Null,
      'ClashSquad' : IDL.Null,
      'LoneWolf' : IDL.Null,
    }),
    'entryFee' : IDL.Int,
    'roomId' : IDL.Opt(IDL.Text),
    'filledSlots' : IDL.Nat,
    'prizePool' : IDL.Int,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PaymentRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'user' : IDL.Principal,
    'timestamp' : Time,
    'amount' : IDL.Int,
  });
  const WithdrawRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'user' : IDL.Principal,
    'timestamp' : Time,
    'upiId' : IDL.Text,
    'amount' : IDL.Int,
  });
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
    'preferNotToSay' : IDL.Null,
  });
  const WalletTransaction = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({ 'pending' : IDL.Null, 'completed' : IDL.Null }),
    'transactionType' : IDL.Variant({
      'withdraw' : IDL.Null,
      'deposit' : IDL.Null,
      'entryFee' : IDL.Null,
      'winning' : IDL.Null,
    }),
    'description' : IDL.Text,
    'timestamp' : Time,
    'amount' : IDL.Int,
  });
  const UserProfile = IDL.Record({
    'languagePreference' : IDL.Text,
    'username' : IDL.Text,
    'phoneNumbers' : IDL.Vec(IDL.Text),
    'winningBalance' : IDL.Int,
    'registeredMatches' : IDL.Vec(IDL.Nat),
    'email' : IDL.Text,
    'gender' : Gender,
    'transactions' : IDL.Vec(WalletTransaction),
    'lastName' : IDL.Text,
    'walletBalance' : IDL.Int,
    'firstName' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMatch' : IDL.Func([TournamentMatch], [], []),
    'addMatchWithToken' : IDL.Func([IDL.Text, TournamentMatch], [], []),
    'addWinningAmountWithToken' : IDL.Func(
        [IDL.Text, IDL.Principal, IDL.Int],
        [],
        [],
      ),
    'approvePaymentRequest' : IDL.Func([IDL.Nat], [], []),
    'approvePaymentWithToken' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'approveWithdrawWithToken' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkEmailExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'checkPhoneExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'checkUsernameExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'deleteMatchWithToken' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'getAllMatches' : IDL.Func([], [IDL.Vec(TournamentMatch)], ['query']),
    'getAllPendingPaymentsWithToken' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PaymentRequest)],
        ['query'],
      ),
    'getAllPendingWithdrawsWithToken' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(WithdrawRequest)],
        ['query'],
      ),
    'getAllUsersWithToken' : IDL.Func(
        [IDL.Text],
        [
          IDL.Vec(
            IDL.Record({ 'principal' : IDL.Principal, 'username' : IDL.Text })
          ),
        ],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMatchesByCategory' : IDL.Func(
        [
          IDL.Variant({
            'BattleRoyale' : IDL.Null,
            'other' : IDL.Null,
            'ClashSquad' : IDL.Null,
            'LoneWolf' : IDL.Null,
          }),
        ],
        [IDL.Vec(TournamentMatch)],
        ['query'],
      ),
    'getRegisteredMatches' : IDL.Func(
        [],
        [IDL.Vec(TournamentMatch)],
        ['query'],
      ),
    'getTransactionHistory' : IDL.Func(
        [],
        [IDL.Vec(WalletTransaction)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWalletBalance' : IDL.Func([], [IDL.Int], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerForMatch' : IDL.Func([IDL.Nat], [], []),
    'rejectPaymentWithToken' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'rejectWithdrawWithToken' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'requestPayment' : IDL.Func([IDL.Int], [], []),
    'requestWithdraw' : IDL.Func([IDL.Int, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateMatchWithToken' : IDL.Func([IDL.Text, TournamentMatch], [], []),
  });
};

export const init = ({ IDL }) => { return []; };