/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface TournamentMatch {
    id: bigint;
    status: Variant_upcoming_live_completed;
    title: string;
    maxSlots: bigint;
    scheduledTime: Time;
    mode: string;
    roomPassword?: string;
    category: Variant_BattleRoyale_other_ClashSquad_LoneWolf;
    entryFee: bigint;
    roomId?: string;
    filledSlots: bigint;
    prizePool: bigint;
}
export interface WalletTransaction {
    id: bigint;
    status: Variant_pending_completed;
    transactionType: Variant_withdraw_deposit_entryFee_winning;
    description: string;
    timestamp: Time;
    amount: bigint;
}
export interface PaymentRequest {
    id: bigint;
    status: Variant_pending_approved_rejected;
    user: Principal;
    timestamp: Time;
    amount: bigint;
}
export interface WithdrawRequest {
    id: bigint;
    status: Variant_pending_approved_rejected;
    user: Principal;
    timestamp: Time;
    upiId: string;
    amount: bigint;
}
export interface UserProfile {
    languagePreference: string;
    username: string;
    phoneNumbers: Array<string>;
    winningBalance: bigint;
    registeredMatches: Array<bigint>;
    email: string;
    gender: Gender;
    transactions: Array<WalletTransaction>;
    lastName: string;
    walletBalance: bigint;
    firstName: string;
}
export enum Gender {
    other = "other",
    female = "female",
    male = "male",
    preferNotToSay = "preferNotToSay"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_BattleRoyale_other_ClashSquad_LoneWolf {
    BattleRoyale = "BattleRoyale",
    other = "other",
    ClashSquad = "ClashSquad",
    LoneWolf = "LoneWolf"
}
export enum Variant_pending_approved_rejected {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum Variant_pending_completed {
    pending = "pending",
    completed = "completed"
}
export enum Variant_upcoming_live_completed {
    upcoming = "upcoming",
    live = "live",
    completed = "completed"
}
export enum Variant_withdraw_deposit_entryFee_winning {
    withdraw = "withdraw",
    deposit = "deposit",
    entryFee = "entryFee",
    winning = "winning"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addMatch(newMatch: TournamentMatch): Promise<void>;
    addMatchWithToken(adminToken: string, newMatch: TournamentMatch): Promise<void>;
    addWinningAmountWithToken(adminToken: string, user: Principal, amount: bigint): Promise<void>;
    approvePaymentRequest(requestId: bigint): Promise<void>;
    approvePaymentWithToken(adminToken: string, requestId: bigint): Promise<void>;
    approveWithdrawWithToken(adminToken: string, requestId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkEmailExists(email: string): Promise<boolean>;
    checkPhoneExists(phone: string): Promise<boolean>;
    checkUsernameExists(username: string): Promise<boolean>;
    deleteMatchWithToken(adminToken: string, matchId: bigint): Promise<void>;
    getAllMatches(): Promise<Array<TournamentMatch>>;
    getAllPendingPaymentsWithToken(adminToken: string): Promise<Array<PaymentRequest>>;
    getAllPendingWithdrawsWithToken(adminToken: string): Promise<Array<WithdrawRequest>>;
    getAllUsersWithToken(adminToken: string): Promise<Array<{
        principal: Principal;
        username: string;
    }>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMatchesByCategory(category: Variant_BattleRoyale_other_ClashSquad_LoneWolf): Promise<Array<TournamentMatch>>;
    getRegisteredMatches(): Promise<Array<TournamentMatch>>;
    getTransactionHistory(): Promise<Array<WalletTransaction>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWalletBalance(): Promise<bigint>;
    isCallerAdmin(): Promise<boolean>;
    registerForMatch(matchId: bigint): Promise<void>;
    rejectPaymentWithToken(adminToken: string, requestId: bigint): Promise<void>;
    rejectWithdrawWithToken(adminToken: string, requestId: bigint): Promise<void>;
    requestPayment(amount: bigint): Promise<void>;
    requestWithdraw(amount: bigint, upiId: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateMatchWithToken(adminToken: string, updatedMatch: TournamentMatch): Promise<void>;
}
import type { Gender as _Gender, PaymentRequest as _PaymentRequest, Time as _Time, TournamentMatch as _TournamentMatch, UserProfile as _UserProfile, UserRole as _UserRole, WalletTransaction as _WalletTransaction, WithdrawRequest as _WithdrawRequest } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addMatch(arg0: TournamentMatch): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMatch(to_candid_TournamentMatch_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMatch(to_candid_TournamentMatch_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addMatchWithToken(arg0: string, arg1: TournamentMatch): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMatchWithToken(arg0, to_candid_TournamentMatch_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMatchWithToken(arg0, to_candid_TournamentMatch_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addWinningAmountWithToken(arg0: string, arg1: Principal, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addWinningAmountWithToken(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWinningAmountWithToken(arg0, arg1, arg2);
            return result;
        }
    }
    async approvePaymentRequest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approvePaymentRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approvePaymentRequest(arg0);
            return result;
        }
    }
    async approvePaymentWithToken(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approvePaymentWithToken(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approvePaymentWithToken(arg0, arg1);
            return result;
        }
    }
    async approveWithdrawWithToken(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveWithdrawWithToken(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveWithdrawWithToken(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkEmailExists(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkEmailExists(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkEmailExists(arg0);
            return result;
        }
    }
    async checkPhoneExists(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkPhoneExists(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkPhoneExists(arg0);
            return result;
        }
    }
    async checkUsernameExists(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkUsernameExists(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkUsernameExists(arg0);
            return result;
        }
    }
    async deleteMatchWithToken(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMatchWithToken(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMatchWithToken(arg0, arg1);
            return result;
        }
    }
    async getAllMatches(): Promise<Array<TournamentMatch>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMatches();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMatches();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPendingPaymentsWithToken(arg0: string): Promise<Array<PaymentRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPendingPaymentsWithToken(arg0);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPendingPaymentsWithToken(arg0);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPendingWithdrawsWithToken(arg0: string): Promise<Array<WithdrawRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPendingWithdrawsWithToken(arg0);
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPendingWithdrawsWithToken(arg0);
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsersWithToken(arg0: string): Promise<Array<{
        principal: Principal;
        username: string;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsersWithToken(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsersWithToken(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMatchesByCategory(arg0: Variant_BattleRoyale_other_ClashSquad_LoneWolf): Promise<Array<TournamentMatch>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatchesByCategory(to_candid_variant_n4(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatchesByCategory(to_candid_variant_n4(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRegisteredMatches(): Promise<Array<TournamentMatch>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRegisteredMatches();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRegisteredMatches();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactionHistory(): Promise<Array<WalletTransaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionHistory();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionHistory();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWalletBalance(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getWalletBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWalletBalance();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async registerForMatch(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerForMatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerForMatch(arg0);
            return result;
        }
    }
    async rejectPaymentWithToken(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectPaymentWithToken(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectPaymentWithToken(arg0, arg1);
            return result;
        }
    }
    async rejectWithdrawWithToken(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectWithdrawWithToken(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectWithdrawWithToken(arg0, arg1);
            return result;
        }
    }
    async requestPayment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestPayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestPayment(arg0);
            return result;
        }
    }
    async requestWithdraw(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestWithdraw(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestWithdraw(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n32(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n32(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateMatchWithToken(arg0: string, arg1: TournamentMatch): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMatchWithToken(arg0, to_candid_TournamentMatch_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMatchWithToken(arg0, to_candid_TournamentMatch_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Gender_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentRequest_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentRequest): PaymentRequest {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_TournamentMatch_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TournamentMatch): TournamentMatch {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_WalletTransaction_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WalletTransaction): WalletTransaction {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawRequest_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawRequest): WithdrawRequest {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: {
        pending: null;
    } | {
        approved: null;
    } | {
        rejected: null;
    };
    user: Principal;
    timestamp: _Time;
    amount: bigint;
}): {
    id: bigint;
    status: Variant_pending_approved_rejected;
    user: Principal;
    timestamp: Time;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_variant_n16(_uploadFile, _downloadFile, value.status),
        user: value.user,
        timestamp: value.timestamp,
        amount: value.amount
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: {
        pending: null;
    } | {
        approved: null;
    } | {
        rejected: null;
    };
    user: Principal;
    timestamp: _Time;
    upiId: string;
    amount: bigint;
}): {
    id: bigint;
    status: Variant_pending_approved_rejected;
    user: Principal;
    timestamp: Time;
    upiId: string;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_variant_n16(_uploadFile, _downloadFile, value.status),
        user: value.user,
        timestamp: value.timestamp,
        upiId: value.upiId,
        amount: value.amount
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    languagePreference: string;
    username: string;
    phoneNumbers: Array<string>;
    winningBalance: bigint;
    registeredMatches: Array<bigint>;
    email: string;
    gender: _Gender;
    transactions: Array<_WalletTransaction>;
    lastName: string;
    walletBalance: bigint;
    firstName: string;
}): {
    languagePreference: string;
    username: string;
    phoneNumbers: Array<string>;
    winningBalance: bigint;
    registeredMatches: Array<bigint>;
    email: string;
    gender: Gender;
    transactions: Array<WalletTransaction>;
    lastName: string;
    walletBalance: bigint;
    firstName: string;
} {
    return {
        languagePreference: value.languagePreference,
        username: value.username,
        phoneNumbers: value.phoneNumbers,
        winningBalance: value.winningBalance,
        registeredMatches: value.registeredMatches,
        email: value.email,
        gender: from_candid_Gender_n23(_uploadFile, _downloadFile, value.gender),
        transactions: from_candid_vec_n25(_uploadFile, _downloadFile, value.transactions),
        lastName: value.lastName,
        walletBalance: value.walletBalance,
        firstName: value.firstName
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: {
        pending: null;
    } | {
        completed: null;
    };
    transactionType: {
        withdraw: null;
    } | {
        deposit: null;
    } | {
        entryFee: null;
    } | {
        winning: null;
    };
    description: string;
    timestamp: _Time;
    amount: bigint;
}): {
    id: bigint;
    status: Variant_pending_completed;
    transactionType: Variant_withdraw_deposit_entryFee_winning;
    description: string;
    timestamp: Time;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_variant_n28(_uploadFile, _downloadFile, value.status),
        transactionType: from_candid_variant_n29(_uploadFile, _downloadFile, value.transactionType),
        description: value.description,
        timestamp: value.timestamp,
        amount: value.amount
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: {
        upcoming: null;
    } | {
        live: null;
    } | {
        completed: null;
    };
    title: string;
    maxSlots: bigint;
    scheduledTime: _Time;
    mode: string;
    roomPassword: [] | [string];
    category: {
        BattleRoyale: null;
    } | {
        other: null;
    } | {
        ClashSquad: null;
    } | {
        LoneWolf: null;
    };
    entryFee: bigint;
    roomId: [] | [string];
    filledSlots: bigint;
    prizePool: bigint;
}): {
    id: bigint;
    status: Variant_upcoming_live_completed;
    title: string;
    maxSlots: bigint;
    scheduledTime: Time;
    mode: string;
    roomPassword?: string;
    category: Variant_BattleRoyale_other_ClashSquad_LoneWolf;
    entryFee: bigint;
    roomId?: string;
    filledSlots: bigint;
    prizePool: bigint;
} {
    return {
        id: value.id,
        status: from_candid_variant_n10(_uploadFile, _downloadFile, value.status),
        title: value.title,
        maxSlots: value.maxSlots,
        scheduledTime: value.scheduledTime,
        mode: value.mode,
        roomPassword: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.roomPassword)),
        category: from_candid_variant_n12(_uploadFile, _downloadFile, value.category),
        entryFee: value.entryFee,
        roomId: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.roomId)),
        filledSlots: value.filledSlots,
        prizePool: value.prizePool
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upcoming: null;
} | {
    live: null;
} | {
    completed: null;
}): Variant_upcoming_live_completed {
    return "upcoming" in value ? Variant_upcoming_live_completed.upcoming : "live" in value ? Variant_upcoming_live_completed.live : "completed" in value ? Variant_upcoming_live_completed.completed : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    BattleRoyale: null;
} | {
    other: null;
} | {
    ClashSquad: null;
} | {
    LoneWolf: null;
}): Variant_BattleRoyale_other_ClashSquad_LoneWolf {
    return "BattleRoyale" in value ? Variant_BattleRoyale_other_ClashSquad_LoneWolf.BattleRoyale : "other" in value ? Variant_BattleRoyale_other_ClashSquad_LoneWolf.other : "ClashSquad" in value ? Variant_BattleRoyale_other_ClashSquad_LoneWolf.ClashSquad : "LoneWolf" in value ? Variant_BattleRoyale_other_ClashSquad_LoneWolf.LoneWolf : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): Variant_pending_approved_rejected {
    return "pending" in value ? Variant_pending_approved_rejected.pending : "approved" in value ? Variant_pending_approved_rejected.approved : "rejected" in value ? Variant_pending_approved_rejected.rejected : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    female: null;
} | {
    male: null;
} | {
    preferNotToSay: null;
}): Gender {
    return "other" in value ? Gender.other : "female" in value ? Gender.female : "male" in value ? Gender.male : "preferNotToSay" in value ? Gender.preferNotToSay : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
}): Variant_pending_completed {
    return "pending" in value ? Variant_pending_completed.pending : "completed" in value ? Variant_pending_completed.completed : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    withdraw: null;
} | {
    deposit: null;
} | {
    entryFee: null;
} | {
    winning: null;
}): Variant_withdraw_deposit_entryFee_winning {
    return "withdraw" in value ? Variant_withdraw_deposit_entryFee_winning.withdraw : "deposit" in value ? Variant_withdraw_deposit_entryFee_winning.deposit : "entryFee" in value ? Variant_withdraw_deposit_entryFee_winning.entryFee : "winning" in value ? Variant_withdraw_deposit_entryFee_winning.winning : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PaymentRequest>): Array<PaymentRequest> {
    return value.map((x)=>from_candid_PaymentRequest_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WithdrawRequest>): Array<WithdrawRequest> {
    return value.map((x)=>from_candid_WithdrawRequest_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WalletTransaction>): Array<WalletTransaction> {
    return value.map((x)=>from_candid_WalletTransaction_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TournamentMatch>): Array<TournamentMatch> {
    return value.map((x)=>from_candid_TournamentMatch_n8(_uploadFile, _downloadFile, x));
}
function to_candid_Gender_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function to_candid_TournamentMatch_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TournamentMatch): _TournamentMatch {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n33(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_WalletTransaction_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WalletTransaction): _WalletTransaction {
    return to_candid_record_n38(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: Variant_upcoming_live_completed;
    title: string;
    maxSlots: bigint;
    scheduledTime: Time;
    mode: string;
    roomPassword?: string;
    category: Variant_BattleRoyale_other_ClashSquad_LoneWolf;
    entryFee: bigint;
    roomId?: string;
    filledSlots: bigint;
    prizePool: bigint;
}): {
    id: bigint;
    status: {
        upcoming: null;
    } | {
        live: null;
    } | {
        completed: null;
    };
    title: string;
    maxSlots: bigint;
    scheduledTime: _Time;
    mode: string;
    roomPassword: [] | [string];
    category: {
        BattleRoyale: null;
    } | {
        other: null;
    } | {
        ClashSquad: null;
    } | {
        LoneWolf: null;
    };
    entryFee: bigint;
    roomId: [] | [string];
    filledSlots: bigint;
    prizePool: bigint;
} {
    return {
        id: value.id,
        status: to_candid_variant_n3(_uploadFile, _downloadFile, value.status),
        title: value.title,
        maxSlots: value.maxSlots,
        scheduledTime: value.scheduledTime,
        mode: value.mode,
        roomPassword: value.roomPassword ? candid_some(value.roomPassword) : candid_none(),
        category: to_candid_variant_n4(_uploadFile, _downloadFile, value.category),
        entryFee: value.entryFee,
        roomId: value.roomId ? candid_some(value.roomId) : candid_none(),
        filledSlots: value.filledSlots,
        prizePool: value.prizePool
    };
}
function to_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    languagePreference: string;
    username: string;
    phoneNumbers: Array<string>;
    winningBalance: bigint;
    registeredMatches: Array<bigint>;
    email: string;
    gender: Gender;
    transactions: Array<WalletTransaction>;
    lastName: string;
    walletBalance: bigint;
    firstName: string;
}): {
    languagePreference: string;
    username: string;
    phoneNumbers: Array<string>;
    winningBalance: bigint;
    registeredMatches: Array<bigint>;
    email: string;
    gender: _Gender;
    transactions: Array<_WalletTransaction>;
    lastName: string;
    walletBalance: bigint;
    firstName: string;
} {
    return {
        languagePreference: value.languagePreference,
        username: value.username,
        phoneNumbers: value.phoneNumbers,
        winningBalance: value.winningBalance,
        registeredMatches: value.registeredMatches,
        email: value.email,
        gender: to_candid_Gender_n34(_uploadFile, _downloadFile, value.gender),
        transactions: to_candid_vec_n36(_uploadFile, _downloadFile, value.transactions),
        lastName: value.lastName,
        walletBalance: value.walletBalance,
        firstName: value.firstName
    };
}
function to_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: Variant_pending_completed;
    transactionType: Variant_withdraw_deposit_entryFee_winning;
    description: string;
    timestamp: Time;
    amount: bigint;
}): {
    id: bigint;
    status: {
        pending: null;
    } | {
        completed: null;
    };
    transactionType: {
        withdraw: null;
    } | {
        deposit: null;
    } | {
        entryFee: null;
    } | {
        winning: null;
    };
    description: string;
    timestamp: _Time;
    amount: bigint;
} {
    return {
        id: value.id,
        status: to_candid_variant_n39(_uploadFile, _downloadFile, value.status),
        transactionType: to_candid_variant_n40(_uploadFile, _downloadFile, value.transactionType),
        description: value.description,
        timestamp: value.timestamp,
        amount: value.amount
    };
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_upcoming_live_completed): {
    upcoming: null;
} | {
    live: null;
} | {
    completed: null;
} {
    return value == Variant_upcoming_live_completed.upcoming ? {
        upcoming: null
    } : value == Variant_upcoming_live_completed.live ? {
        live: null
    } : value == Variant_upcoming_live_completed.completed ? {
        completed: null
    } : value;
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    other: null;
} | {
    female: null;
} | {
    male: null;
} | {
    preferNotToSay: null;
} {
    return value == Gender.other ? {
        other: null
    } : value == Gender.female ? {
        female: null
    } : value == Gender.male ? {
        male: null
    } : value == Gender.preferNotToSay ? {
        preferNotToSay: null
    } : value;
}
function to_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_pending_completed): {
    pending: null;
} | {
    completed: null;
} {
    return value == Variant_pending_completed.pending ? {
        pending: null
    } : value == Variant_pending_completed.completed ? {
        completed: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_BattleRoyale_other_ClashSquad_LoneWolf): {
    BattleRoyale: null;
} | {
    other: null;
} | {
    ClashSquad: null;
} | {
    LoneWolf: null;
} {
    return value == Variant_BattleRoyale_other_ClashSquad_LoneWolf.BattleRoyale ? {
        BattleRoyale: null
    } : value == Variant_BattleRoyale_other_ClashSquad_LoneWolf.other ? {
        other: null
    } : value == Variant_BattleRoyale_other_ClashSquad_LoneWolf.ClashSquad ? {
        ClashSquad: null
    } : value == Variant_BattleRoyale_other_ClashSquad_LoneWolf.LoneWolf ? {
        LoneWolf: null
    } : value;
}
function to_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_withdraw_deposit_entryFee_winning): {
    withdraw: null;
} | {
    deposit: null;
} | {
    entryFee: null;
} | {
    winning: null;
} {
    return value == Variant_withdraw_deposit_entryFee_winning.withdraw ? {
        withdraw: null
    } : value == Variant_withdraw_deposit_entryFee_winning.deposit ? {
        deposit: null
    } : value == Variant_withdraw_deposit_entryFee_winning.entryFee ? {
        entryFee: null
    } : value == Variant_withdraw_deposit_entryFee_winning.winning ? {
        winning: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<WalletTransaction>): Array<_WalletTransaction> {
    return value.map((x)=>to_candid_WalletTransaction_n37(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
